const ACTIONS = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_DATA: "SET_DATA",
  LOAD_MORE: "LOAD_MORE",
  SET_LOAD_MORE_DATA: "SET_LOAD_MORE_DATA",
  LOAD_MORE_ERROR: "LOAD_MORE_ERROR",
  SET_QUERY: "SET_QUERY"
} as const;

export { ACTIONS };
